### ISSUE TITLE
Where is code repo for Quick guide to large language models?

### ISSUE THREAD

**Issue by andysingal** [sinanuozdemir/quick-start-guide-to-llms#1]
Hello ,
     Greetings!!
     While reading your book, I was looking for code for fast api for document chunking but was not able to find the repo. Can you please share the repo.
Thanks,
Ankush Singal

**Comment by sinanuozdemir** [comment]
I made a big update today for the launch of the book so hopefully everything is here now for you to read over! If you're still missing something, please let me know :)
