### ISSUE TITLE
Chapter 3: Is "get_best_result_from_pinecone()" implementation correct?

### ISSUE THREAD

**Issue by udooz** [sinanuozdemir/quick-start-guide-to-llms#11]
Hi,

This function post the payload into "**https://information-retrieval-hiaa.onrender.com/document/retrieve**" and not doing any interactions with PineCode.  As per Figure 3.12 and the relevant sections it is mentioned that Retrieve result from Vector database.  I'm unable to see any thing in the Chapter #3 Notebook.

Please help me understand.

```
def get_best_result_from_pinecone(query, namespace=NAMESPACE):
    payload = json.dumps({
      "num_results": 2,
      "query": query,
      "re_ranking_strategy": "none",
      "namespace": namespace
    })

    response = requests.post(
        "https://information-retrieval-hiaa.onrender.com/document/retrieve",
        data=payload
    )
```

**Comment by sinanuozdemir** [comment]
The implementation is correct but my pinecone index had gone to sleep (It's on the free plan :)) I woke it up and now it should be working now! Be sure to check out the [notebook in Chapter 2](notebooks/2_semantic_search.ipynb) to see how to spin up your own index and the API file [here](semantic-search-fastapi/api.py) to try and spin up your own API as well :) 

Hope this helps!
