### ISSUE TITLE
Dataset "amazon_reviews_multi" is defunct and no longer accessible due to the decision of data providers

### ISSUE THREAD

**Issue by udooz** [sinanuozdemir/quick-start-guide-to-llms#12]
Hi @sinanuozdemir,

This is to just notify you that the dataset "amazon_reviews_multi" is disabled by author.  https://huggingface.co/datasets/amazon_reviews_multi.  Looking forward your recommended alternate.

Regards,
Sheik

**Comment by sinanuozdemir** [comment]
Thanks for posting! I addressed this in #6 with a new notebook!
https://github.com/sinanuozdemir/quick-start-guide-to-llms/blob/main/notebooks/UPDATED%204_fine_tuned_classification_sentiment.ipynb

Unfortunately I can't change the book now but the 2nd edition will reflect the new dataset

**Comment by udooz** [comment]
Thanks for the update @sinanuozdemir.  I missed out to see the UPDATED version.
