### ISSUE TITLE
Not working any more with v>1

### ISSUE THREAD

**Issue by don-alberto** [sinanuozdemir/quick-start-guide-to-llms#13]
Even if I explicitely install  openai-0.28.1, I get 

**APIRemovedInV1**: 

_You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API._

You probably want to update the course on o'really eather, otherwise the code is not working

**Comment by sinanuozdemir** [comment]
You're so right that I need to make these updates for v 1.0 in a few places! As of now my thought is to make a new branch for the latest openai versions and keep main as is written in the book for clarity. Let me know your thoughts on that.

If you're seeing that APIRemoved error, you may not have 0.28.1 installed. Here is some colab code where I very clearly have 0.28.1 installed and the embedding code should be working as I originally wrote it. Which line of code were you getting this error for? I'd be happy to help here :) 


<img width="722" alt="Screenshot 2024-01-03 at 9 43 28 AM" src="https://github.com/sinanuozdemir/quick-start-guide-to-llms/assets/3695746/c37dad03-1b96-4b82-a8e3-4c57a6a65980">

**Comment by don-alberto** [comment]
Now this is my bad, downgraded to 0.28.1 in the wrong env.
Now everything is working like a charm. I am just a product owner wanting to understand what my devs are doin.
Purchased your course on O'Reily and trying to step through.
Great course so far!

**Comment by sinanuozdemir** [comment]
I'm glad! I'm here if you have questions :). Closing this for now.
