### ISSUE TITLE
Update Chapter 6 Anime Recommendation Engine with updated metrics and more fine-tuning

### ISSUE THREAD

**Issue by sinanuozdemir** [sinanuozdemir/quick-start-guide-to-llms#14]
I've been working on an updated version of the Chapter 6 recommendation engine case study and will be posting a new notebook soon!

**Comment by sinanuozdemir** [comment]
@lftuwujie2023 I am working on this new update here: [https://colab.research.google.com/drive/1JfxyxdGCDjYeO52Bk1JzW4Af94xndTws?usp=sharing](https://colab.research.google.com/drive/1JfxyxdGCDjYeO52Bk1JzW4Af94xndTws?usp=sharing)

I'd love to get your thoughts 😄

**Comment by lftuwujie2023** [comment]
@sinanuozdemir Thanks for sharing this again. I think this part looks like incorrect, please see the updated version below. If I was wrong please let me know.

# Looping over each pair of animes
for a1, a2 in tqdm(anime_pairs):
    # print(a1, a2)
    # If any of the animes in the pair is not found in the pre_merged_anime dataframe index, we skip the current iteration
    """I think these 2 lines can either be removed (because a1 and a2 are already in the pre_merged_anime, we don't need to check them again).
    Or. Use my modified lines, because a1 and a2 are MAL_ID not the index of  pre_merged_anime"""
#     if a1 not in pre_merged_anime.index or a2 not in pre_merged_anime.index:
#         continue
    if a1 not in pre_merged_anime.MAL_ID.unique.tolist() or a2 not in pre_merged_anime.MAL_ID.unique.tolist():
        continue

    # Calculating Jaccard similarity between the sets of users who like anime a1 and anime a2
    # j = jaccard_similarity(user_anime_dict.get(a1, set()), user_anime_dict.get(a2, set()))
    j = anime_pair_scores(a1, a2)
    all_scores.append(j)

    # If the similarity is non-zero (i.e., there are some common users)
    if j is not None:
        # If similarity is greater than or equal to 0.8,
        # then the pair is considered as a positive example and added to the positive_pairs_examples list
        """Same as above, a1 and a2 are the MAL_ID, they are not the index of pre_merged_anime, so we should use these lines below."""
#         if j >= 0.8:
#             positive_pairs_examples.append(InputExample(texts=[pre_merged_anime.loc[a1]['generated_description'], pre_merged_anime.loc[a2]['generated_description']], label=j))
        if j >= 0.8:
            positive_pairs_examples.append(InputExample(texts=[pre_merged_anime[pre_merged_anime['MAL_ID']==a1]['generated_description'],
                                                               pre_merged_anime[pre_merged_anime['MAL_ID']==a2]['generated_description']], label=j))

        # If similarity is less than -0.8,
        # then the pair is considered as a negative example and added to the negative_pairs_examples list
#         elif j < -0.8:
#             negative_pairs_examples.append(InputExample(texts=[pre_merged_anime.loc[a1]['generated_description'], pre_merged_anime.loc[a2]['generated_description']], label=j))
        elif j < -0.8:
            negative_pairs_examples.append(InputExample(texts=[pre_merged_anime[pre_merged_anime['MAL_ID']==a1]['generated_description'],
                                                               pre_merged_anime[pre_merged_anime['MAL_ID']==a2]['generated_description']], label=j))

**Comment by lftuwujie2023** [comment]
Hi @sinanuozdemir Thanks again for sharing the updated version. However, I think there still are some errors in the attached screenshot. Please have a look and let me know if i was wrong or misunderstood it.

![Screenshot 2024-01-11 at 21 44 20](https://github.com/sinanuozdemir/quick-start-guide-to-llms/assets/154092184/234a4e6b-154e-49dd-94cb-c063c516c917)

**Comment by sinanuozdemir** [comment]
Hey! I ended up making some more changes as well after I got over a bad case of COVID. I think it's looking pretty well! I'm gearing up to write a 2nd edition and I want to make this case study top notch.

**Comment by lftuwujie2023** [comment]
@sinanuozdemir Thanks for the updating, and I am really sorry to heard that you got bad case of COVID, hope you are better now. I aslo got very bad flu/cold in the last 10 days. 

The new updated version looks pretty tidy. Can you please let me know when your 2nd edition of book is ready? I really looking forward to getting it on my hands.
