### ISSUE TITLE
Chapter 2 Notebook errors

### ISSUE THREAD

**Issue by pdeitel** [sinanuozdemir/quick-start-guide-to-llms#15]
Hi Sinan,

Trying to run your Chapter 2 notebook. When I get to 

```python
import pinecone

pinecone.init(api_key=pinecone_key, environment="us-west1-gcp")
```

it issues an error that "init is no longer a top-level attribute of the pinecone package." Then it gives the following replacement code:

```python
    import os
    from pinecone import Pinecone, ServerlessSpec

    pc = Pinecone(
        api_key=os.environ.get("PINECONE_API_KEY")
    )

    # Now do stuff
    if 'my_index' not in pc.list_indexes().names():
        pc.create_index(
            name='my_index', 
            dimension=1536, 
            metric='euclidean',
            spec=ServerlessSpec(
                cloud='aws',
                region='us-west-2'
            )
        )
```

When I try the replacement code, I get this error:

```
PineconeApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=utf-8', 'access-control-allow-origin': '*', 'vary': 'origin,access-control-request-method,access-control-request-headers', 'access-control-expose-headers': '*', 'X-Cloud-Trace-Context': 'a4dd30976b4a3a292eb49f325c69da3b', 'Date': 'Sun, 28 Jan 2024 22:21:38 GMT', 'Server': 'Google Frontend', 'Content-Length': '125', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: {"error":{"code":"INVALID_ARGUMENT","message":"Name must consist of lower case alphanumeric characters or '-'"},"status":400}
```

Do you have an updated working notebook?

**Comment by sinanuozdemir** [comment]
Thanks for the note! I'm working on a new version of this notebook to be released this week! It will have updated code for pinecone's latest package version and also using OpenAI's latest embedding model: https://openai.com/blog/new-embedding-models-and-api-updates

**Comment by pdeitel** [comment]
Thanks Sinan!

I also noticed that your requirements.txt file is incomplete.

As I tried to run various notebooks, I had to install additional Python packages, such as pinecone. I encountered this with some of the Chapter 8 notebooks, too. I have not run the 3-7 notebooks yet.

It would be great if the requirements.txt included all the packages you use throughout your notebooks.

Best,
Paul


From: Sinan Ozdemir ***@***.***>
Date: Monday, January 29, 2024 at 9:52 AM
To: sinanuozdemir/quick-start-guide-to-llms ***@***.***>
Cc: Paul Deitel ***@***.***>, Author ***@***.***>
Subject: Re: [sinanuozdemir/quick-start-guide-to-llms] Chapter 2 Notebook errors (Issue #15)

Thanks for the note! I'm working on a new version of this notebook to be released this week! It will have updated code for pinecone's latest package version and also using OpenAI's latest embedding model: https://openai.com/blog/new-embedding-models-and-api-updates

**Comment by sinanuozdemir** [comment]
Oh! Thank you again! I will go through and add them one by one as I find them. It's with help from people like you that a single author can keep all of this up to date and accurate :)

**Comment by pdeitel** [comment]
😊 I’ll keep you posted of anything else I find.

From: Sinan Ozdemir ***@***.***>
Date: Monday, January 29, 2024 at 10:21 AM
To: sinanuozdemir/quick-start-guide-to-llms ***@***.***>
Cc: Paul Deitel ***@***.***>, Author ***@***.***>
Subject: Re: [sinanuozdemir/quick-start-guide-to-llms] Chapter 2 Notebook errors (Issue #15)

Oh! Thank you again! I will go through and add them one by one as I find them. It's with help from people like you that a single author can keep all of this up to date and accurate :)

**Comment by sinanuozdemir** [comment]
I have an updated version here in colab! https://github.com/sinanuozdemir/quick-start-guide-to-llms/commit/a282c4add4fa2f74df8b52cadd19ad4000fbfdc0

I commented out the clustering stuff to get the openai + pinecone working. I intend to clean it up for the 2nd edition coming out later this year!
