### ISSUE TITLE
No module named 'dotenv'

### ISSUE THREAD

**Issue by greenorca** [sinanuozdemir/quick-start-guide-to-llms#16]
After installing the required modules in a virtual environment on Ubuntu (pip3 install -r requirements.txt), I cannot run the fastapi:  uvicorn api:app  --reload because dotenv is missing.

It seems, _pip3 install python-dotenv_ solves the problem. Maybe it can be added to the requirements.txt.

**Comment by sinanuozdemir** [comment]
Thanks for the heads up! I added it per your suggestion :)
