### ISSUE TITLE
Pinecone, You've reach the max pod-based indexes allowed in project Chatbot

### ISSUE THREAD

**Issue by sacrificium-dev** [sinanuozdemir/quick-start-guide-to-llms#18]
I am actually reading your book, cloned this repo and just wanted to start the FastAPI-server:

`uvicorn api:app  --reload`

The server wont start with the following error:

``` 
pinecone.core.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=utf-8', 'x-pinecone-api-version': '2024-04', 'access-control-allow-origin': '*', 'vary': 'origin,access-control-request-method,access-control-request-headers', 'access-control-expose-headers': '*', 'X-Cloud-Trace-Context': 'dda0306cba028ae7c9df198988881253', 'Date': 'Wed, 26 Jun 2024 09:27:07 GMT', 'Server': 'Google Frontend', 'Content-Length': '136', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: Request failed. You've reach the max pod-based indexes allowed in project Chatbot (0). To add more pod-based indexes, upgrade your plan.

INFO:     Stopping reloader process [15896]
```

See:
https://docs.pinecone.io/reference/quotas-and-limits#pod-based-indexes-per-project

Is it intended to have another plan than Standard on pinecone? Thought it should work under standard as well, to be able to play around with the book-examples?

Thank you very much!

**Comment by sinanuozdemir** [comment]
Hi and thanks for making an issue! I wrote this when pinecone had different plans set up and my most recent update should resolve the most recent commit! [https://github.com/sinanuozdemir/quick-start-guide-to-llms/commit/0485d8303b99993723d40dc7c9fa2a65bda19fbe](https://github.com/sinanuozdemir/quick-start-guide-to-llms/commit/0485d8303b99993723d40dc7c9fa2a65bda19fbe)

I'm about to update a lot of the code in a new branch to get ready for the 2nd edition in October and this code will be a part of that too.

Let me know if this helps and I can close the issue.

**Comment by sacrificium-dev** [comment]
Thank you very much and sorry for my late response. With that update you can close the issue, thats enough for me.

**Comment by sinanuozdemir** [comment]
Glad to hear and let me know if you have any other issues! I'm happy to help.
