### ISSUE TITLE
chapter 3-4 mentions Fast openai

### ISSUE THREAD

**Issue by andysingal** [sinanuozdemir/quick-start-guide-to-llms#4]
Hi Sinan,
     Thanks for the amazing book, any chance to add the fastAPI code as mentioned and how it interacts?. So that it interacts as mentioned in Chapters 2-4
<img width="774" alt="Screenshot 2023-09-14 at 10 07 00 PM" src="https://github.com/sinanuozdemir/quick-start-guide-to-llms/assets/20493493/f8086932-9d95-44dc-a123-f9ec8422f3e4">

Looking forward to hearing from you.
Thanks,
Andy

**Comment by sinanuozdemir** [comment]
Hey! My most recent commit adds that code in :) cd2cd578006d72703a849e2a18884b8753c7a11a
