### ISSUE TITLE
depricated amazon_reviews_multi dataset

### ISSUE THREAD

**Issue by dgamma3** [sinanuozdemir/quick-start-guide-to-llms#6]
chapter 4 talks about Optimizing LLMs with Customized Fine-Tuning using amazon_reviews_multi dataset, however this is deprecated @sinanuozdemir 

https://github.com/huggingface/datasets/issues/6109#issuecomment-1661632183

**Comment by sinanuozdemir** [comment]
Oh my goodness good eye! I must have missed this after I wrote the chapter. Any suggestions for what to replace with? It's too late for the book haha but I can least make a new notebook with the new dataset and use that for the 2nd edition.

Thank you for calling this out :)

**Comment by sinanuozdemir** [comment]
For everyone following, I am about to release a new notebook using the dataset: https://huggingface.co/datasets/app_reviews.

I am also updating the code to use the newest OpenAI fine-tuning API. The next edition of the book will have these updates eventually!
