### ISSUE TITLE
Remove env file from semantic-search-fastapi folder.

### ISSUE THREAD

**Issue by mjsiers** [sinanuozdemir/quick-start-guide-to-llms#7]
Noticed that the .env file in the semantic-search-fastapi folder was checked into the repository.
Probably need to update your .gitignore file, remove the file and regenerated your API keys
to ensure they are deactivated.

**Comment by sinanuozdemir** [comment]
Thank you for looking out! I really do appreciate it. I did put in the README in that folder:

`Note the .env file in there is on purpose and NONE of those keys work. They are there purely for demonstration purposes.`

I included the file for those who may be unfamiliar with how to set up .env files. I know when I was first starting out developing it took me an embarrassing amount of time to realize how to structure the .env file so I just wanted to include it to leave no room for doubt :) 

Those keys should both be not working but if you're seeing something different, please let me know!
